name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - uses: actions/checkout@v2

      - name: Build
        run: go build github.com/martinvw/go-search-string/cmd/search-string

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "search-string"
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}
